language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
cache: bundler
before_install:
  - mkdir -p $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - curl -L https://www.dropbox.com/s/577u8h68gbpkpzz/texmath?dl=1 -o $HOME/bin/texmath
  - chmod +x $HOME/bin/texmath
