language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  fast_finish: true
cache: bundler
before_install:
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install -fexecutable texmath
  - export PATH=$HOME/.cabal/bin:$PATH
