language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby-20mode # JRuby in 1.9 mode
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
cache: bundler
before_install:
  - sudo apt-get install haskell-platform
  - cabal update
  - cabal install -fexecutable texmath
